sudo systemctl stop kiwix

# Edit the drop-in that is overriding everything
sudo nano /etc/systemd/system/kiwix.service.d/override.conf

sudo nano /etc/systemd/system/kiwix.service.d/  and
sudo nano /etc/systemd/system/kiwix.service.d/override.conf

[Service]
User=kiwix
Group=media
UMask=0002

sudo systemctl daemon-reload
sudo systemctl start kiwix

systemctl show kiwix -p ExecStart --no-pager
sudo ss -lntp | grep ':8090' || true
curl -I http://127.0.0.1:8090/ | head

ip -4 -o addr show scope global | awk '{split($4,a,"/"); print a[1]}' | head -n1

sudo tee /etc/systemd/system/kiwix.service.d/10-execstart.conf >/dev/null <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/bin/kiwix-serve -v -i 192.168.0.205 -p 8090 /opt/appdata/kiwix/data/zims/freecodecamp_en_coding-interview-prep_2025-11.zim
EOF

sudo systemctl daemon-reload
sudo systemctl restart kiwix


